### ISSUE TITLE
vercel 배포 후 신규 컨텐츠가 업데이트 안되는 이슈

### ISSUE THREAD

**Issue by breezjin** [2skydev/Notion-Next.js-blog-starter-kit#43]
안녕하세요. 이것저것 툴들을 둘러보다 여기까지 왔네요.
한가지 궁금한게 로컬에서 돌리면 ISR이 잘 돌아가는데,
vercel에 배포만 하면 먹통이 되는 이슈가 있습니다.

이 부분 때문에 골머리를 썩고 있네요;;
혹시 아이디어가 있으실까요?

감사합니다~

**Comment by 2skydev** [comment]
혹시 아래 화면과 같이 Vercel의 Function 로그를 확인해보셨나요?
로그 페이지를 들어간 후 배포한 블로그에 접속하면 실시간으로 로그가 표시되는데 이때 오류가 없는지 확인 부탁드립니다 :)

스크린샷 첨부가 가능하다면 `Show Details` 버튼을 눌러 자세한 로그를 표시한 후 코멘트 달아주세요.

![image](https://user-images.githubusercontent.com/43225384/209321736-9d2e0fb0-05d8-4f27-9203-04bdb158dea2.png)

**Comment by breezjin** [comment]
코멘트 감사 드려요! vercel에서 이런 로그도 볼 수 있었군요!
revalidate 주기의 문제인걸까요? 흠...

<img width="1248" alt="CleanShot 2022-12-24 at 13 33 18@2x" src="https://user-images.githubusercontent.com/29007384/209421397-69652815-1937-43bf-ac71-bfb0972f91b2.png">

**Comment by 2skydev** [comment]
에러 내용을 확인해보니 `Serverless Function Execution Timeout` 으로 최대 실행시간 초과되어서 오류가 발생한 것 같습니다.

Notion? Vercel의 문제인건지 정확히는 모르겠지만 저도 최근에 실행시간 10초를 넘겨서 오류가 뜨는 경우가 있습니다.

## 해결방안
플랜을 변경하거나 따로 서버를(AWS, GCP 등) 설정해야 됩니다.

기본 플랜은 최대 10초이며 프로 플랜부터는 60초까지 가능합니다. [플랜 링크](https://vercel.com/pricing)

![image](https://user-images.githubusercontent.com/43225384/209422655-0f63328c-f34a-4035-92ab-8442b4482354.png)

**Comment by breezjin** [comment]
안그래도 로컬에서는 문제가 없고, 배포 이후에 발생하는 문제라서 인프라 이슈일거 같았는데 다시 한번 체크해봐야겠네요.
조언으로 많은 부분이 해소되는거 같네요! 감사합니다 :)
