### ISSUE TITLE
스크롤바 표시

### ISSUE THREAD

**Issue by sy9777m** [2skydev/Notion-Next.js-blog-starter-kit#52]
안녕하세요, 제공해주신 템플릿 사용해서 너무 잘 사용하고 있습니다.

커스텀을 딱 입맛에 맞게 해주셔서, 기존 오리지날 프로젝트보다 배포해주신 프로젝트로 블로그를 배포하게 됐습니다.

그런데 스크롤바가 표시되지 않는 아쉬움이 있어서, 업데이트 부탁드리려고 이렇게 이슈 남깁니다.

**Comment by sy9777m** [comment]
scss 수정해서 해결했습니다! ㅎㅎ

**Comment by 2skydev** [comment]
포스트 상세 우측에 현재 읽고 있는 위치가 표시되어 디자인을 위해 스크롤바를 표시하지 않았습니다 :D
스크롤바가 필요하다면 scss 파일을 수정해서 사용하시면 됩니다. 감사합니다!
