### ISSUE TITLE
안녕하세요! 구글 애널리틱스 혹은 검색처리에대해 질문이있습니다.

### ISSUE THREAD

**Issue by jungsikjeong** [2skydev/Notion-Next.js-blog-starter-kit#61]
혹시 구글 애널리틱스나, 구글에서 검색이 되게끔하는걸 사용할 수있을까요? 
@2skydev 님은 어떻게 하셧나요?
아니면 노션 자체적인 애널리틱스(?)를 사용하시는걸까요??

**Comment by 2skydev** [comment]
단순히 구글 애널과 서치 콘솔만 등록해두었습니다 :)
