### ISSUE TITLE
구글  서치콘솔 질문있습니다.

### ISSUE THREAD

**Issue by jungsikjeong** [2skydev/Notion-Next.js-blog-starter-kit#67]
nextjs-google-analytics` 라이브러리로 인해서 vercel에 환경변수로 구글애널리틱스 id(?) 만 넣어주면 자동으로
구글 서치콘솔에도 등록이 되는걸까요?

**Comment by 2skydev** [comment]
넵넵 맞습니다

자세한 내용은 아래 링크 참고해주세요
https://github.com/2skydev/Notion-Next.js-blog-starter-kit/wiki/GA-%EA%B5%AC%EC%84%B1%ED%95%98%EA%B8%B0-(Google-Analytics)

**Comment by jungsikjeong** [comment]
@2skydev  감사합니다. 이미 설명을 작성하셨는데 제가 못찾았었네욤..:)
