### ISSUE TITLE
구글 서치콘솔에 등록 어떻게하셨을까요?

### ISSUE THREAD

**Issue by jungsikjeong** [2skydev/Notion-Next.js-blog-starter-kit#68]
안녕하세요 블로그 테마 잘 이용하고있습니다!

저번에도 같은 제목의 글을 올렸는데 제가 잘못 이해하고 글을 올린것 같습니다.

저번 글에서는 구글 애널등록방법의 문의였었는데..

이번 이슈 글은 구글서치콘솔 등록 방법 문의입니다.

구글에 블로그이름 검색하면 뜨게하는거는 어떻게 설정하셨을까요?

sitemap.xml을 깃에 올려 커밋하면 vercel에서 충돌에러가 나서 골치아프네유,,

**Comment by 2skydev** [comment]
sitemap 같은 경우 따로 파일을 생성하는게 아닌 /sitemap.xml 으로 요청 시 확인 가능합니다 😃 
자세한 내용은 아래 링크를 확인해주세요!

https://github.com/2skydev/Notion-Next.js-blog-starter-kit/blob/main/pages/sitemap.xml.tsx

**Comment by jungsikjeong** [comment]
> sitemap 같은 경우 따로 파일을 생성하는게 아닌 /sitemap.xml 으로 요청 시 확인 가능합니다 😃
자세한 내용은 아래 링크를 확인해주세요!

> https://github.com/2skydev/Notion-Next.js-blog-starter-kit/blob/main/pages/sitemap.xml.tsx

@2skydev  헉,,정말 감사합니다. 제 지식이 부족해서 발생한 헤프닝이네요. 빠른 답변도 감사합니다!
